### PR TITLE
Add minimal example for geom_count

### PR DESCRIPTION
**Pull request by joshhartmann11**

### CODE REVIEW

**Comment by has2k1** [comment]
Thanks. As more people are using plotnine with minimal python experience, not to flagrantly violate "best practices" the examples no longer use `*` imports. I just realised I had not pushed the changes.

The images are now retina quality. 

Ref: https://github.com/has2k1/plotnine-examples/blob/main/plotnine_examples/examples/geom_col.ipynb

**Comment by orsinium** [comment]
I always do `import plotnine as gg` 🙃

**Comment by has2k1** [comment]
> I always do `import plotnine as gg` 🙃


The most common alias being used is `p9`. As using plotnine involves many pieces, an alias creates a little too much clutter for my eyes. So it is `*` for notebooks and explicit imports in script files.

I have occasionally used the hybrid approach and I find it tolerable. But I have not seen it anywhere else.

```python
import plotnine as p9
from plotnine import ggplot, aes, after_stat, theme
```

**Comment by joshhartmann11** [comment]
I am also guilty of `import plotnine as gg` :upside_down_face:. I've updated the example. Thanks!

**Comment by has2k1** [comment]
> I am also guilty of `import plotnine as gg` 🙃.

Ehh, this is a pandemic!

**Comment by has2k1** [comment]
@joshhartmann11, Thank you.

**Pull request merged**
