### PR TITLE
Created example notebook for plots updated with ipywidgets.

### PR DESCRIPTION
**Pull request by melomcr**
This simple example shows how ipywidgets can be used to *interactively* select sub-sets of data to be plotted with plotnine.

ipywidgets have to be installed and activated (used version 7.1.2).

Even using the "matplotlib.pyplot.tight_layout" function, the initial plotnine figure show part of the legend outside the figure box. Manually resizing the figure (dragging the corner to increase the figure size) fixes the rendering issue, but I don't know how to fix the issue automatically.

### CODE REVIEW

**Comment by has2k1** [comment]
Great.

I think this code should be hidden in a function provided by plotnine.

```python
def draw_xxx(p, fig, axs):
    if fig is None:
        # If this is the first time a plot is made in the notebook, we let plotnine create a new 
        # matplotlib figure and axis.
        fig, plot = p.draw(return_ggplot=True)
        axs = plot.axs
    else:
        
        #p = copy(p)
        # This helps keeping old selected data from being visualized after a new selection is made.
        # We delete all previously reated artists from the matplotlib axis.
        for artist in plt.gca().lines +\
                        plt.gca().collections +\
                        plt.gca().artists + plt.gca().patches + plt.gca().texts:
            artist.remove()
        
        # If a plot is being updated, we re-use the figure an axis created before.
        p._draw_using_figure(fig, axs)
    return fig, axs
```

There is a similarity with how animations work, but for them MPL cleans up the artists. I think this may not be the last time that this pattern shows up.

**Comment by melomcr** [comment]
That would probably be  the best solution. I will certainly be using this piece of code all the time.

I can update the notebook example to have it in a separate function for now (while plotnine doesn't offer the function explicitly), but I think we should keep the function code explicit while the function isn't natively offered. Is that ok?
I can offer a pull request in plotnine's git repo to create the function as a top level module method.

Options that come to mind: 
`draw_live(p, fig=None, axs=None)`
draw_notebook
draw_continuous

The one issue is that people need to know to use `%matplotlib notebook` in their cells. it's quite annoying to have to deal with a statefull infrastructure for a stateless package... 

Any thoughts on function name and/or warning regarding %matplotlib call?

**Comment by has2k1** [comment]
I am a bit hang up -- due to the statefull-stateless clash. As a result I think there are going be some edge-cases but I am lacking in creativity to enumerate any of them.

For the name, the best I have is `draw_redraw`. I think most users trying to use ipywidgets will use the
`%matplotlib notebook` line magic. For users who discover widgets through plotnine, then the example should be sufficient. Usually, the magic line in the *first cell* of the notebook.

You can submit a PR for the function. Put it in a `plotnine/tools.py`! 

Also, the file for this PR should go in the  tutorials folder, so that it can show up [here](http://plotnine.readthedocs.io/en/stable/tutorials.html). Prefix the file name with `using-` and put a descriptive header (`#`) at the top.

**Comment by melomcr** [comment]
(bump) I came back to the repo to check the code for the "redraw" function and noticed that I forgot to finish the changes you suggested a long time ago. I put the notebook under "Tutorials" and created a file with the `draw_redraw` function under "tools".

@has2k1 , Looks ok? Let me know if you need any other changes.

I have already used this code in 4 or 5 different notebooks by now and it is really useful, so the example/tutorial should help some people out there.

**Comment by orsinium** [comment]
@melomcr, that's wonderful! You've done great work. Now I'm going through this PR to let it go. However, I have issues with running it: when I change cylinders count in any cylinder it just puts an empty chart below old one instead of updating it with correct data. Code in the 2204d2805705e2f928efc56ef85ffcaf0dd633b2 work. Could you have a look at it, please?

image

Also, please, add a few lines at the beginning about [ipywidgets installation](https://ipywidgets.readthedocs.io/en/stable/user_install.html), it would be really helpful.

What about `draw_redraw`, there is a little misunderstanding. @has2k1 meant to contribute it into [plotnine](https://github.com/has2k1/plotnine/) itself. Let's keep it into this notebook till next plotnine release.

**Comment by melomcr** [comment]
@orsinium , Thank you!
The new figures used to show up when the matplotlib magic wasn't used, but maybe some code change made it behave differently.
I'll take a look at that and commit the necessary modifications, plus the ipywidgets info you mentioned.

**Comment by orsinium** [comment]
Oh, I've looked again, and it was my mistake. I've not properly installed ipywidgets. Now it works. I've added installation info and dropped matplotlib warnings. Thank you for your contribution :)

**Comment by orsinium** [comment]
And I've committed into original master instead of your fork >.<

**Pull request merged**
