### PR TITLE
Added box plot examples

### PR DESCRIPTION
**Pull request by orsinium**
Thank you for the great lib. Plotnine has obvious lack of documentation, and I want to help you a little bit with it :)

Examples based on [ggplot2 docs](https://ggplot2.tidyverse.org/reference/geom_boxplot.html).

### CODE REVIEW

**Comment by has2k1** [comment]
Thank you.

**Comment by orsinium** [comment]
I'm happy to help you ^^ Merge?

**Comment by orsinium** [comment]
@has2k1, could you review my pull requests, please?

**Comment by orsinium** [comment]
@has2k1, is the project maintained?

**Comment by has2k1** [comment]
@orsinium, Yes it is. I somehow just tend to forget about it until a release of plotnine ready.

**Comment by orsinium** [comment]
Why did you send me an invitation to the project? Do you want me to help you with reviews?

**Comment by orsinium** [comment]
- [x] Correct cells order
- [x] No warnings
- [x] Correct rendering in Sphinx

**Pull request merged**
