### PR TITLE
Add order plot series tutorial

### PR DESCRIPTION
**Pull request by Steve-Fry**
**Change:**
Add tutorial for how to setup sorted series for plots using pandas ordered categorical abilities.

**Comment:** 
This is my first attempt at contributing, so just me know if I'm missing any conventions. 

Regards
Steve

### CODE REVIEW

**Comment by has2k1** [comment]
The narrative is great, but the ordered plot is kinda unemphatic compared the one [at](has2k1/plotnine/issues/94). I think, many users look at graphs first then maybe read on how to replicate them. The `elements` data may not be the best.

Two other issues

- `coord_flip` the final graph too
- add your name to `contributors.txt`

Also, if your system (esp. OSX or linux) allows, you can use the following command to execute the notebook before you commit.

```bash
$ make changes
```

It excludes any unnecessary warnings.

**Comment by Steve-Fry** [comment]
Thanks for the feedback!

This should be a bit closer. I dropped the narrative tone, answers are much more interesting than words. 

Is this the direction you had in mind? 

Sadly I don't have make available in my environment (windows), I have tried to emulate the steps taken by the makefile but if there is anything missing I can spin up a vm to run it.

Thanks

**Comment by has2k1** [comment]
> Is this the direction you had in mind?

Nothing too particular. The objective is to have the tutorials be readable without getting distracted by the code.

> ... but if there is anything missing I can spin up a vm to run it.

No worries, I can easily do that. And, I'll be making a change to the command. Thank you.

**Comment by Steve-Fry** [comment]
Many thanks!

**Pull request merged**
